spring:
  main:
    banner-mode: OFF
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: "myGroup"
      auto-offset-reset: "earliest"
      enable-auto-commit: "true"code
      auto-commit-interval: 1000
#    schema:"
#      registry-url: "http://schema-registry:8081"